### ISSUE TITLE
Time between retries doesn't work?

### ISSUE THREAD

**Issue by kadimski** [ncla/LoungeDestroyer#153] opened 2015-01-24 11:18 UTC
Since the update i haven't been able to select time between bet retries on CSGO Lounge, it does auto bet but the time betweenretries is like 14 seconds and when I type some value it doesn't work anyway.

**Comment by ncla** [comment] 2015-01-24 11:24
How doesn't it work? Does it reset to the old delay value? Do you type the value and it gets ignored? It doesn't save?

**Comment by kadimski** [comment] 2015-01-24 11:26
Ignored, just does some random time

**Comment by kadimski** [comment] 2015-01-24 11:30
Btw it's on Chrome, how can I install an earlier version, earlier releases have worked

**Comment by ncla** [comment] 2015-01-24 13:11
Are you using other extensions? Did you try restarting your browser? Tried reinstalling LD?

Does the console log (press F12 to open, then press Console tab) say anything (when changing the values for example)?

**Comment by kadimski** [comment] 2015-01-24 15:26
Nevermind I think it started to work again. But yeah I did reinstall it a couple of times, adblock is the only extension i use.

**Comment by kadimski** [comment] 2015-01-24 20:13
Ehm it's stuck to 2,3 seconds or something and the console doesn't show anything when I switch time.

**Comment by birjolaxew** [comment] 2015-01-24 20:53
Could you [add me on Steam](http://steamcommunity.com/id/birjolaxew)?

**Comment by kadimski** [comment] 2015-01-24 21:58
I added you

**Comment by birjolaxew** [comment] 2015-01-25 14:00
Unable to reproduce, closing

**Closed by birjolaxew** 2015-01-25 14:00 UTC
